# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
