# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='user',
            field=models.ManyToManyField(related_name='user', to='logreg.User'),
        ),
    ]
