# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
